# Generated by Django 4.2.11 on 2024-04-22 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('O', 'Открыто'), ('W', 'В работе'), ('T', 'Тестирование'), ('D', 'Выполнено')], default='O', max_length=1, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('priority', models.CharField(blank=True, choices=[('H', 'Высокий'), ('A', 'Средний'), ('L', 'Низкий')], default='L', max_length=1, verbose_name='Приоритет')),
                ('seriousness', models.CharField(blank=True, choices=[('S1', 'Блокирующая'), ('S2', 'Критическая'), ('S3', 'Значительная'), ('S4', 'Незначительная'), ('S5', 'Тривиальная')], default='S5', max_length=2, verbose_name='Серьезность бага')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('playback_steps', models.TextField(blank=True, max_length=250, verbose_name='Шаги воспроизведения')),
                ('actual_result', models.CharField(blank=True, max_length=250, verbose_name='Фактический результат')),
                ('expected_result', models.CharField(blank=True, max_length=250, verbose_name='Ожидаемый результат')),
                ('context', models.CharField(blank=True, max_length=150, verbose_name='Окружение')),
                ('attachments', models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name='Вложения')),
                ('more_information', models.TextField(blank=True, max_length=250, verbose_name='Дополнительная информация')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['log']), django.core.validators.MaxLengthValidator(1048576)], verbose_name='Файл лога')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение от пользователя',
                'verbose_name_plural': 'Сообщения от пользователей',
            },
        ),
    ]
