# Generated by Django 4.2.11 on 2024-04-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_report',
            old_name='user',
            new_name='user_id',
        ),
    ]
