# Generated by Django 4.2.11 on 2024-04-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0002_rename_user_user_report_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_report',
            old_name='user_id',
            new_name='user',
        ),
    ]
