# Generated by Django 4.2.11 on 2024-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0004_alter_user_report_actual_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_report',
            name='status',
            field=models.CharField(choices=[('O', 'Открыто'), ('W', 'В работе'), ('T', 'Тестирование'), ('D', 'Выполнено')], default='O', max_length=1, verbose_name='Статуc'),
        ),
    ]
